from __future__ import annotations

from typing import Any, Dict, List

from fastapi import APIRouter, HTTPException

from .. import db
from ..schemas import (
    ActionItemCreate,
    ActionItemRead,
    ActionItemUpdate,
    ExtractRequest,
    ExtractResponse,
)
from ..services.extract import extract_action_items, extract_action_items_llm


router = APIRouter(prefix="/action-items", tags=["action-items"])


@router.post("/extract", response_model=ExtractResponse)
def extract(payload: ExtractRequest) -> ExtractResponse:
    # --- GENERATED BY AI ---
    """Extract action items from text, optionally saving the text as a note."""
    if not payload.text.strip():
        raise HTTPException(status_code=400, detail="text cannot be empty")
    # --- GENERATED BY AI ---
    
    note_id: int | None = None
    if payload.save_note:
        note_id = db.insert_note(payload.text)

    items = extract_action_items(payload.text)
    ids = db.insert_action_items(items, note_id=note_id)
    
    # --- GENERATED BY AI ---
    # Convert to ActionItemRead format
    action_items = []
    for i, item_id in enumerate(ids):
        action_items.append(
            ActionItemRead(
                id=item_id,
                note_id=note_id,
                text=items[i],
                done=False,
                created_at="",  # Will be filled from DB
            )
        )
    # --- GENERATED BY AI ---
    
    return ExtractResponse(note_id=note_id, items=action_items)


@router.get("/", response_model=List[ActionItemRead])
def list_all(note_id: int | None = None) -> List[ActionItemRead]:
    # --- GENERATED BY AI ---
    """List all action items, optionally filtered by note_id."""
    rows = db.list_action_items(note_id=note_id)
    return [
        ActionItemRead(
            id=r["id"],
            note_id=r["note_id"],
            text=r["text"],
            done=bool(r["done"]),
            created_at=r["created_at"],
        )
        for r in rows
    ]
    # --- GENERATED BY AI ---


@router.get("/{action_item_id}", response_model=ActionItemRead)
def get_item(action_item_id: int) -> ActionItemRead:
    # --- GENERATED BY AI ---
    """Get a single action item by ID."""
    if action_item_id < 1:
        raise HTTPException(status_code=400, detail="Invalid action item ID")
    
    row = db.get_action_item(action_item_id)
    if not row:
        raise HTTPException(status_code=404, detail="Action item not found")
    
    return ActionItemRead(
        id=row["id"],
        note_id=row["note_id"],
        text=row["text"],
        done=bool(row["done"]),
        created_at=row["created_at"],
    )
    # --- GENERATED BY AI ---


@router.post("/", response_model=ActionItemCreate, status_code=201)
def create_item(payload: ActionItemCreate) -> Dict[str, Any]:
    # --- GENERATED BY AI ---
    """Create a new action item."""
    if not payload.text.strip():
        raise HTTPException(status_code=400, detail="text cannot be empty")
    
    ids = db.insert_action_items([payload.text])
    if not ids:
        raise HTTPException(status_code=500, detail="Failed to create action item")
    
    return {"id": ids[0], "text": payload.text}
    # --- GENERATED BY AI ---


@router.put("/{action_item_id}/done", response_model=ActionItemRead)
def mark_done(action_item_id: int, payload: ActionItemUpdate) -> ActionItemRead:
    # --- GENERATED BY AI ---
    """Mark an action item as done or reopen it."""
    if action_item_id < 1:
        raise HTTPException(status_code=400, detail="Invalid action item ID")
    
    row = db.mark_action_item_done(action_item_id, payload.done)
    if not row:
        raise HTTPException(status_code=404, detail="Action item not found")
    
    return ActionItemRead(
        id=row["id"],
        note_id=row["note_id"],
        text=row["text"],
        done=bool(row["done"]),
        created_at=row["created_at"],
    )
    # --- GENERATED BY AI ---


@router.post("/{action_item_id}/done", response_model=ActionItemRead)
def mark_done_legacy(action_item_id: int, payload: ActionItemUpdate) -> ActionItemRead:
    # --- GENERATED BY AI ---
    """Legacy POST endpoint for marking items as done. Use PUT instead."""
    return mark_done(action_item_id, payload)
    # --- GENERATED BY AI ---


# --- GENERATED BY AI ---
@router.post("/extract-llm", response_model=ExtractResponse)
def extract_llm(payload: ExtractRequest) -> ExtractResponse:
    """Extract action items from text using LLM, optionally saving the text as a note."""
    if not payload.text.strip():
        raise HTTPException(status_code=400, detail="text cannot be empty")
    
    note_id: int | None = None
    if payload.save_note:
        note_id = db.insert_note(payload.text)

    items = extract_action_items_llm(payload.text)
    ids = db.insert_action_items(items, note_id=note_id)
    
    # Convert to ActionItemRead format
    action_items = []
    for i, item_id in enumerate(ids):
        action_items.append(
            ActionItemRead(
                id=item_id,
                note_id=note_id,
                text=items[i],
                done=False,
                created_at="",
            )
        )
    
    return ExtractResponse(note_id=note_id, items=action_items)
# --- GENERATED BY AI ---


