from __future__ import annotations

from typing import Any, Dict, List

from fastapi import APIRouter, HTTPException

from .. import db
from ..schemas import NoteRead


router = APIRouter(prefix="/notes", tags=["notes"])


@router.post("")
def create_note(payload: Dict[str, Any]) -> Dict[str, Any]:
    content = str(payload.get("content", "")).strip()
    if not content:
        raise HTTPException(status_code=400, detail="content is required")
    note_id = db.insert_note(content)
    note = db.get_note(note_id)
    return {
        "id": note["id"],
        "content": note["content"],
        "created_at": note["created_at"],
    }


# --- GENERATED BY AI ---
@router.get("/", response_model=List[NoteRead])
def list_all_notes() -> List[NoteRead]:
    """List all notes ordered by creation date (newest first)."""
    rows = db.list_notes()
    return [
        NoteRead(
            id=r["id"],
            content=r["content"],
            created_at=r["created_at"],
        )
        for r in rows
    ]
# --- GENERATED BY AI ---


@router.get("/{note_id}", response_model=NoteRead)
def get_single_note(note_id: int) -> NoteRead:
    # --- GENERATED BY AI ---
    """Get a single note by ID."""
    if note_id < 1:
        raise HTTPException(status_code=400, detail="Invalid note ID")
    
    row = db.get_note(note_id)
    if row is None:
        raise HTTPException(status_code=404, detail="note not found")
    
    return NoteRead(
        id=row["id"],
        content=row["content"],
        created_at=row["created_at"],
    )
    # --- GENERATED BY AI ---


