import os
import pytest

from ..app.services.extract import extract_action_items
from ..app.services.extract import extract_action_items_llm
from ..app.services.extract import extract_action_items_llm
from ..app.services.extract import extract_action_items_llm


def test_extract_bullets_and_checkboxes():
    text = """
    Notes from meeting:
    - [ ] Set up database
    * implement API extract endpoint
    1. Write tests
    Some narrative sentence.
    """.strip()

    items = extract_action_items(text)
    assert "Set up database" in items
    assert "implement API extract endpoint" in items
    # --- GENERATED BY AI ---
def test_extract_action_items_llm_with_bullets():
        
        text = """
        - Fix the bug in login
        * Update documentation
        1. Deploy to production
        """.strip()
        
        items = extract_action_items_llm(text)
        assert isinstance(items, list)
        assert len(items) > 0


def test_extract_action_items_llm_with_keywords():
        
        text = """
        TODO: Review pull requests
        ACTION: Schedule team meeting
        NEXT: Implement feature X
        """.strip()
        
        items = extract_action_items_llm(text)
        assert isinstance(items, list)
        assert len(items) > 0


def test_extract_action_items_llm_empty_string():
        
        text = ""
        items = extract_action_items_llm(text)
        assert isinstance(items, list)
        assert len(items) == 0
    # --- GENERATED BY AI ---
