from __future__ import annotations

import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Optional


BASE_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BASE_DIR / "data"
DB_PATH = DATA_DIR / "app.db"


def ensure_data_directory_exists() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)


@contextmanager
def get_connection() -> sqlite3.Connection:
    # --- GENERATED BY AI ---
    """Context manager for database connections with automatic cleanup."""
    ensure_data_directory_exists()
    connection = sqlite3.connect(str(DB_PATH))
    connection.row_factory = sqlite3.Row
    try:
        yield connection
    finally:
        connection.close()
    # --- GENERATED BY AI ---


def init_db() -> None:
    """Initialize database with required tables."""
    ensure_data_directory_exists()
    with get_connection() as connection:
        cursor = connection.cursor()
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS notes (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                content TEXT NOT NULL,
                created_at TEXT DEFAULT (datetime('now'))
            );
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS action_items (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                note_id INTEGER,
                text TEXT NOT NULL,
                done INTEGER DEFAULT 0,
                created_at TEXT DEFAULT (datetime('now')),
                FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE
            );
            """
        )
        # --- GENERATED BY AI ---
        # Add indexes for better query performance
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_action_items_note_id ON action_items(note_id);"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_action_items_done ON action_items(done);"
        )
        # --- GENERATED BY AI ---
        connection.commit()


def insert_note(content: str) -> int:
    with get_connection() as connection:
        cursor = connection.cursor()
        cursor.execute("INSERT INTO notes (content) VALUES (?)", (content,))
        connection.commit()
        return int(cursor.lastrowid)


def list_notes() -> list[sqlite3.Row]:
    """List all notes ordered by creation date (newest first)."""
    with get_connection() as connection:
        cursor = connection.cursor()
        cursor.execute("SELECT id, content, created_at FROM notes ORDER BY created_at DESC")
        return list(cursor.fetchall())


def get_note(note_id: int) -> Optional[sqlite3.Row]:
    """Get a single note by ID."""
    # --- GENERATED BY AI ---
    if note_id < 1:
        return None
    # --- GENERATED BY AI ---
    with get_connection() as connection:
        cursor = connection.cursor()
        cursor.execute(
            "SELECT id, content, created_at FROM notes WHERE id = ?",
            (note_id,),
        )
        return cursor.fetchone()


def insert_action_items(items: list[str], note_id: Optional[int] = None) -> list[int]:
    """Insert multiple action items and return their IDs."""
    # --- GENERATED BY AI ---
    if not items:
        return []
    # --- GENERATED BY AI ---
    with get_connection() as connection:
        cursor = connection.cursor()
        ids: list[int] = []
        for item in items:
            cursor.execute(
                "INSERT INTO action_items (note_id, text) VALUES (?, ?)",
                (note_id, item),
            )
            ids.append(int(cursor.lastrowid))
        connection.commit()
        return ids


def list_action_items(note_id: Optional[int] = None) -> list[sqlite3.Row]:
    """List action items, optionally filtered by note_id."""
    with get_connection() as connection:
        cursor = connection.cursor()
        if note_id is None:
            cursor.execute(
                "SELECT id, note_id, text, done, created_at FROM action_items ORDER BY created_at DESC"
            )
        else:
            # --- GENERATED BY AI ---
            if note_id < 1:
                return []
            # --- GENERATED BY AI ---
            cursor.execute(
                "SELECT id, note_id, text, done, created_at FROM action_items WHERE note_id = ? ORDER BY created_at DESC",
                (note_id,),
            )
        return list(cursor.fetchall())


def mark_action_item_done(action_item_id: int, done: bool) -> Optional[sqlite3.Row]:
    # --- GENERATED BY AI ---
    """Mark an action item as done/not done and return the updated item."""
    if action_item_id < 1:
        return None
    # --- GENERATED BY AI ---
    with get_connection() as connection:
        cursor = connection.cursor()
        cursor.execute(
            "UPDATE action_items SET done = ? WHERE id = ?",
            (1 if done else 0, action_item_id),
        )
        connection.commit()
        
        # --- GENERATED BY AI ---
        # Fetch updated item to return
        cursor.execute(
            "SELECT id, note_id, text, done, created_at FROM action_items WHERE id = ?",
            (action_item_id,),
        )
        return cursor.fetchone()
        # --- GENERATED BY AI ---


def get_action_item(action_item_id: int) -> Optional[sqlite3.Row]:
    # --- GENERATED BY AI ---
    """Get a single action item by ID."""
    if action_item_id < 1:
        return None
    # --- GENERATED BY AI ---
    with get_connection() as connection:
        cursor = connection.cursor()
        cursor.execute(
            "SELECT id, note_id, text, done, created_at FROM action_items WHERE id = ?",
            (action_item_id,),
        )
        return cursor.fetchone()


