from __future__ import annotations

from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles

from .db import init_db
from .routers import action_items, notes
from . import db

# --- GENERATED BY AI ---
# Initialize database on startup
init_db()

app = FastAPI(
    title="Action Item Extractor",
    description="Extract and manage action items from notes",
    version="0.1.0",
)
# --- GENERATED BY AI ---


@app.get("/", response_class=HTMLResponse)
def index() -> str:
    html_path = Path(__file__).resolve().parents[1] / "frontend" / "index.html"
    try:
        return html_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        raise HTTPException(status_code=500, detail="Frontend not found")


app.include_router(notes.router)
app.include_router(action_items.router)


# --- GENERATED BY AI ---
# Mount static files
static_dir = Path(__file__).resolve().parents[1] / "frontend"
if static_dir.exists():
    app.mount("/static", StaticFiles(directory=str(static_dir)), name="static")
# --- GENERATED BY AI ---


# --- GENERATED BY AI ---
@app.exception_handler(ValueError)
async def value_error_handler(request, exc):
    return HTTPException(status_code=400, detail=str(exc))
# --- GENERATED BY AI ---